### ISSUE TITLE
Is there a reason for different SIMD word choices?

### ISSUE THREAD

**Issue by TheIronBorn** [vks/xoshiro#1]
In the SIMD version, it seems you have chosen different words for various operations.  For example: https://github.com/vks/xoshiro/blob/8783637a39bb6e232420d01c10c4441c481adda9/src/lib.rs#L63
uses the last word for the output. 

But the regular version uses the "canonical" first word: https://github.com/vks/xoshiro/blob/8783637a39bb6e232420d01c10c4441c481adda9/src/lib.rs#L35

**Comment by vks** [comment]
This is intentional! Note that `_mm_extract_epi32` indexes from right to
left, so all indices `i` have to be replaced with `3 - i`. I have a test to
make sure both implementations produce the same output.

Thank you for checking out the code, it's in a super early stage, so it
still needs a lot of work.

**Comment by TheIronBorn** [comment]
Ah, I guess I'm too familiar with stdsimd's abstractions
