### ISSUE TITLE
`from_seed` should not panic

### ISSUE THREAD

**Issue by dhardy** [vks/xoshiro#4]
https://github.com/vks/xoshiro/blob/56abee4c114d9026435878b6b56f56a862caa910/src/xoroshiro128plus.rs#L93

`from_seed` does not have error handling, and we decided that it shouldn't panic [doc](https://rust-random.github.io/rand/rand_core/trait.SeedableRng.html#tymethod.from_seed).

Compare with [this implementation](https://github.com/pitdicker/small-rngs/blob/master/src/xoroshiro_mt.rs#L23).

**Comment by vks** [comment]
I fixed and also made sure that the xoshiro generators are not initialized with all zeros in 0.4.

**Comment by dhardy** [comment]
Okay. That's slightly obscure (i.e. might not be obvious to others what happens) but does the job.

**Comment by vks** [comment]
I'm not sure what you mean. What would be a less obscure alternative?

**Comment by dhardy** [comment]
Choose a substitute seed directly instead of referring to another function which essentially just picks a different seed for you. Mr Dicker had fun with hex constants here ("odd biases", "bad seed") but it doesn't really matter what.

Potentially the compiler can constantise the function result anyway; I just thought it odd that you're essentially just picking another seed value but not admitting it.

**Comment by vks** [comment]
>  I just thought it odd that you're essentially just picking another seed value but not admitting it.

I'm confused, this is exactly what I'm saying in the docs:
```rust
    /// Create a new `Xoshiro256StarStar`.  If `seed` is entirely 0, it will be
    /// mapped to a different seed.
```

There are two reasons I didn't pick magic constants:
1. I don't want to come up with a constant that has too many zeros and is potentially not optimal. Using `SplitMix64` instead seems like a more conservative option, it's the officially recommended way to seed Vigna's generators.
2. The size of the seeds is different for the different generators, so the implementation with a constant would be less uniform. (This could be easily fixed by a wrapper function that throws away superfluous bits though.)
